name: Release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v2
            - name: Add NodeJS
              id: addNode
              uses: actions/setup-node@v1
              with:
                  node-version: "14"
            - name: Run Prerequisites
              id: runPrerequisites
              env:
                  GH_CLI_AUTH_TOKEN: ${{secrets.GH_CLI_AUTH_TOKEN}}
                  GH_EMAIL: ${{ secrets.GH_EMAIL }}
                  GH_NAME: ${{ secrets.GH_NAME }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
                  echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ./.npmrc
                  git config --global user.email "$GH_EMAIL"
                  git config --global user.name "$GH_NAME"
                  echo $GH_CLI_AUTH_TOKEN > gh.txt
                  gh auth login --with-token < gh.txt
                  yarn install
                  rm gh.txt
            - name: Run Monorepo Build Script
              id: monorepoBuild
              run: yarn node -r ts-node/register ./build.ts
            - name: Log into Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: withonevision/omnihive
                  file: ./omnihive.dockerfile
                  context: ./
            - name: Get Version Number
              id: version
              run: echo "::set-output name=VERSION::$(node -p -e "require('./dist/packages/omnihive/package.json').version")"
            - name: Create GitHub Release
              run: |
                  gh release create ${{ steps.version.outputs.VERSION }} ./omnihive.tgz
