name: Release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Yarn Install
              run: yarn
            - name: Build and Publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
                  yarn node -r ts-node/register ./build.ts
            - name: Log into Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: withonevision/omnihive
                  file: ./omnihive.dockerfile
                  context: ./
            - name: Version Number
              id: version
              run: echo "::set-output name=VERSION::$(node -p -e "require('./dist/packages/omnihive/package.json').version")"
            - name: Log into GitHub CLI
              run: |
                  echo ${{secrets.GH_CLI_AUTH_TOKEN}} > gh.txt
                  gh auth login --with-token < gh.txt
            - name: Create GitHub Release
              run: |
                  tar -czvf omnihive.tar.gz ./dist/packages/omnihive
                  gh release create ${{ steps.version.outputs.VERSION }} omnihive.tar.gz
